interface playerData {
  name: string,
  dimension: number,
  x: number,
  y: number,
  z: number,
  telephone: number,
  hasTelephone: number,
  useMegaphone: number,
  useMicrophone: number,
  transceiverType: number,
  transceiverNumber: number,
  mute: number,
  volumeOutput: number,
  voiceRangeInput: number,
  volumeInput: number,
}